services:
  frontend:
    build: .
    #image: animal-report
    ports:
      - "8080:80"
    restart: unless-stopped

  # backend:
  #   image: reports-aopi
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db
  #   restart: unless-stopped
